name: Clicker
main: ru.FIRST_114.Clicker.Main
version: 1.0
api-version: 1.13 
commands:
    clickerset:
        description: установка кликера
        usage: /clickerset
        permission: clicker.set
    clicks:
        description: Удаление счёта
        usage: /clicks <число>
        permission: clicker.set
    clicker:
        description: кликер
        usage: /clickerset
permissions: #права
    clicker.set:
        description: Your description
depend: [Multiverse-Core]